# .gitpod.yml
image: gitpod/workspace-full

tasks:
  - init: |
      # install backend deps
      cd Backend
      pip install --upgrade pip
      pip install numpy tensorflow pandas fpdf opencv-python matplotlib scikit-image fastapi python-multipart uvicorn
    command: |
      # start backend
      cd Backend
      uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  - init: |
      # install frontend deps
      cd Frontend
      npm install
    command: |
      # start frontend
      cd Frontend
      npm run dev -- --host 0.0.0.0 --port 3000

ports:
  - port: 8000
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
